- project:
    check:
      jobs:
        - openstack-tox-pep8
        - heat-functional
    gate:
      jobs:
        - openstack-tox-pep8
        - heat-functional

    periodic-saturday:
      jobs:
        - heat-functional

- job:
    name: heat-functional
    parent: networking-nuage-base
    branches: ^(?!stable/(newton|ocata)).*$
    timeout: 7800
    override-checkout: stable/stein
    required-projects:
      - name: openstack/heat
      - name: openstack/heat-tempest-plugin
      - name: openstack/oslo.messaging
      - name: openstack/python-heatclient
      - name: openstack/placement
      - name: OpenStack/nuage-gate-utils
      - name: OpenStack/nuage-openstack-neutron
        override-checkout: 6.0/stein
      - name: OpenStack/nuage-openstack-neutronclient
        override-checkout: 6.0/stein
      - name: OpenStack/nuage-openstack-heat
        override-checkout: 6.0/stein
    vars:
      vsp_release: '6.0'
      tempest_plugins:
        - heat-tempest-plugin
        - nuage-tempest-plugin
      devstack_plugins:
        heat: https://opendev.org/openstack/heat
        nuage-openstack-heat: git://git.openstack.org/openstack/nuage-openstack-heat
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
            service_available:
              heat: True
      tempest_test_regex: '^(heat_tempest_plugin\.tests\.functional\.test_create_update_neutron|nuage_tempest_plugin\.tests\.api\.(orchestration|ipv6\.(vsd_managed\.test_orchestration|os_managed\.test_os_managed_dualstack_orchestration))).*'
