- project:
    check:
      jobs:
        - openstack-tox-pep8
        - heat-functional
    gate:
      jobs:
        - openstack-tox-pep8
        - heat-functional

    periodic-saturday:
      jobs:
        - heat-functional

- job:
    name: heat-devstack-base
    parent: legacy-dsvm-base
    run: playbooks/devstack/functional/run.yaml
    post-run: playbooks/devstack/functional/post.yaml
    timeout: 7800
    required-projects:
      - openstack/heat-tempest-plugin
      - openstack/neutron
      - openstack/oslo.messaging
      - openstack/python-heatclient
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-heat
      - OpenStack/nuage-tempest-plugin
      - OpenStack/nuage-openstack-neutron
      - OpenStack/nuage-openstack-neutronclient
    irrelevant-files:
      - ^.*\.rst$
      - ^api-ref/.*$
      - ^doc/.*$
      - ^nuage_heat/locale/.*$
      - ^nuage_heat/tests/.*$
      - ^releasenotes/.*$
    vars:
      disable_convergence: 'false'
      branch_override: stable/rocky

- job:
    name: heat-functional
    parent: heat-devstack-base
    vars:
      disable_convergence: 'true'
