- project:
    check:
      jobs:
        - openstack-tox-pep8
        - heat-functional
    gate:
      jobs:
        - openstack-tox-pep8
        - heat-functional

    periodic-saturday:
      jobs:
        - heat-functional

- job:
    name: heat-functional
    parent: networking-nuage-base
    timeout: 7800
    required-projects:
      - openstack/heat
      - openstack/heat-tempest-plugin
      - openstack/oslo.messaging
      - openstack/python-heatclient
      - OpenStack/nuage-gate-utils
      - OpenStack/nuage-openstack-heat
      - name: openstack/neutron-tempest-plugin
        override-checkout: 0.9.0
    vars:
      tempest_plugins:
        - heat-tempest-plugin
        - nuage-tempest-plugin
      devstack_localrc:
        Q_ML2_TENANT_NETWORK_TYPE: vxlan,vlan,nuage_hybrid_mpls
        Q_ML2_PLUGIN_TYPE_DRIVERS: vxlan,vlan,nuage_hybrid_mpls
      devstack_plugins:
        heat: https://opendev.org/openstack/heat
        nuage-openstack-heat: git://git.openstack.org/openstack/nuage-openstack-heat
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
            service_available:
              heat: True
      tempest_test_regex: '^(heat_tempest_plugin\.tests\.functional\.test_create_update_neutron|nuage_tempest_plugin\.tests\.api\.(orchestration|ipv6\.(vsd_managed\.test_orchestration|os_managed\.test_os_managed_dualstack_orchestration))).*'
