heat_template_version: 2015-04-30
description: >
  Template to illustrate nuage specific attributes for routers.


resources:
  router:
    type: OS::Neutron::Router
    properties:
        name: AppRouter
        value_specs:
            nuage_underlay: 'off'
            nuage_aggregate_flows: 'route'
