heat_template_version: 2013-05-23
description: Template to create a segment of type nuage_hybrid_mpls
parameters:
  net_name:
    type: string
    label: Network Name
    description: The name of the network
  net_type:
    type: string
    label: Network Type
    description: The type of the network
  segment_name:
    type: string
    label: Segment Name
    description: The name of the segment
resources:
  network_mpls:
    type: OS::Neutron::Net
    properties:
      name: { get_param: net_name }
      value_specs: { 'provider:network_type': { get_param: net_type } }
  segment_mpls:
    type: Nuage::Neutron::NuageSegment
    properties:
      name: { get_param: segment_name }
      network: { get_resource: network_mpls }
      network_type: 'nuage_hybrid_mpls'
